# Generated by Django 2.1.4 on 2018-12-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='anon', max_length=50),
            preserve_default=False,
        ),
    ]
