# Generated by Django 2.1.4 on 2018-12-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0002_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.IntegerField(default=27),
        ),
    ]
