# Generated by Django 2.1.4 on 2018-12-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0003_auto_20181219_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='igdb_id',
            field=models.IntegerField(default=None),
        ),
    ]
