# Generated by Django 2.1.4 on 2019-01-08 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodgames', '0005_auto_20190107_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('score', models.IntegerField(default=None)),
                ('date', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodgames.Game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodgames.Profile')),
            ],
        ),
    ]
